# Generated by Django 5.0.3 on 2024-11-27 00:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(blank=True, null=True)),
                ('meter', models.CharField(blank=True, null=True)),
                ('time', models.CharField(blank=True, null=True)),
                ('duration', models.CharField(blank=True, null=True)),
                ('consumption', models.CharField(blank=True, null=True)),
                ('generation', models.CharField(blank=True, null=True)),
                ('net', models.CharField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batterytype', models.CharField(blank=True, max_length=100, null=True)),
                ('utility', models.CharField(blank=True, max_length=100, null=True)),
                ('importGreenButton', models.BooleanField(default=False)),
                ('batterySize', models.IntegerField(default=50)),
                ('solar', models.BooleanField(default=False)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EnergyUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('kwh', models.FloatField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='EnergyUsage', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Optimizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeOfDay', models.TimeField()),
                ('kwh', models.FloatField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Optimizer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Savings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NoBatteryPrice', models.PositiveIntegerField()),
                ('LithiumPrice', models.PositiveIntegerField()),
                ('SodiumPrice', models.PositiveIntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Savings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
