# Generated by Django 5.0.3 on 2024-11-08 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batterytype', models.CharField(blank=True, max_length=100, null=True)),
                ('utility', models.CharField(blank=True, max_length=100, null=True)),
                ('greenbutton', models.BooleanField(default=False)),
                ('battsize', models.FloatField(blank=True, null=True)),
                ('solar', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserExtension', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
