# Generated by Django 5.0.3 on 2024-11-28 00:58

from django.db import migrations, models
import hashlib

def generate_unique_hashes(apps, schema_editor):
    FileModel = apps.get_model('api', 'FileModel')
    for file in FileModel.objects.all():
        # Generate a unique hash based on some fields (e.g., file name and upload date)
        file.file_hash = hashlib.sha256(
            f"Electric_60_Minute_1-1-2024_11-26-2024_20241127".encode('utf-8')
        ).hexdigest()
        file.save()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_filemodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemodel',
            name='file_hash',
            field=models.CharField(max_length=64, unique=False, null=True),
        ),
        migrations.RunPython(generate_unique_hashes),
        migrations.AlterField(
            model_name='filemodel',
            name='file_hash',
            field=models.CharField(max_length=64, unique=False),
        ),
    ]
