# Generated by Django 5.0.3 on 2024-11-28 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_filemodel_file_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='file_hash',
            field=models.CharField(max_length=64),
        ),
    ]
