# Generated by Django 5.0.3 on 2024-11-09 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_userextension_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userextension',
            name='owner',
        ),
        migrations.AddField(
            model_name='userextension',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
