# Generated by Django 5.0.3 on 2024-11-09 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_userextension_owner_userextension_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextension',
            name='battsize',
            field=models.IntegerField(default=50),
        ),
    ]
