# Generated by Django 5.0.3 on 2024-11-09 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_userextension_battsize'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userextension',
            old_name='battsize',
            new_name='battSize',
        ),
        migrations.RenameField(
            model_name='userextension',
            old_name='greenbutton',
            new_name='importGreenButton',
        ),
    ]
