# Generated by Django 5.0.3 on 2024-11-09 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_battsize_userextension_battsize_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userextension',
            old_name='battSize',
            new_name='batterySize',
        ),
    ]
