# Generated by Django 4.2.11 on 2024-04-24 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='image',
            field=models.ImageField(upload_to='thrift\x0crontend\\src\x07ssets'),
        ),
    ]
