# Generated by Django 4.2.11 on 2024-04-24 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_listings_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='image',
            field=models.ImageField(upload_to='C:/Users/Jamal/Documents/GitHub/sdsu-thrift/thrift/backend/media'),
        ),
    ]
