# Generated by Django 4.2.11 on 2024-04-24 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_alter_listings_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='image',
            field=models.ImageField(upload_to='../../frontend/media'),
        ),
    ]
