# Generated by Django 4.2.11 on 2024-04-24 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_alter_listings_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='category',
            field=models.CharField(choices=[('Apparel', 'Apparel'), ('Home Furniture', 'Home Furniture'), ('Free Stuff', 'Free Stuff'), ('Vehicles', 'Vehicles'), ('Toys & Games', 'Toys & Games'), ('Plants & Outdoor', 'Plants & Outdoor'), ('Sporting Goods', 'Sporting Goods'), ('Property Rentals', 'Property Rentals'), ('Pet Supplies', 'Pet Supplies'), ('Hobbies', 'Hobbies'), ('Music Instruments', 'Music Instruments'), ('Textbooks & Books', 'Textbooks & Books'), ('Entertainment', 'Entertainment'), ('Clothes', 'Clothes'), ('Health & Beauty', 'Health & Beauty'), ('Jewelry & Watches', 'Jewelry & Watches'), ('Electronics', 'Electronics'), ('Office Supplies', 'Office Supplies'), ('Seasonal Decorations', 'Seasonal Decorations'), ('Home Appliances', 'Home Appliances')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='listings',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
