# Generated by Django 4.2.11 on 2024-04-24 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_alter_listings_category_alter_listings_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='category',
            field=models.CharField(choices=[('Apparel', 'Apparel'), ('HomeFurniture', 'Home Furniture'), ('Free Stuff', 'Free Stuff'), ('Vehicles', 'Vehicles'), ('Toys&Games', 'Toys & Games'), ('Plants&Outdoor', 'Plants & Outdoor'), ('SportingGoods', 'Sporting Goods'), ('PropertyRentals', 'Property Rentals'), ('PetSupplies', 'Pet Supplies'), ('Hobbies', 'Hobbies'), ('MusicInstruments', 'Music Instruments'), ('Textbooks&Books', 'Textbooks & Books'), ('Entertainment', 'Entertainment'), ('Clothes', 'Clothes'), ('Health&Beauty', 'Health & Beauty'), ('Jewelry&Watches', 'Jewelry & Watches'), ('Electronics', 'Electronics'), ('OfficeSupplies', 'Office Supplies'), ('SeasonalDecorations', 'Seasonal Decorations'), ('HomeAppliances', 'Home Appliances')], max_length=20, null=True),
        ),
    ]
