# Generated by Django 4.2.11 on 2024-05-02 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_alter_listings_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
