# Generated by Django 5.0.3 on 2024-10-09 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShineApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Optimizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeOfDay', models.TimeField()),
                ('kwh', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Savings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NoBatteryPrice', models.PositiveIntegerField()),
                ('LithiumPrice', models.PositiveIntegerField()),
                ('SodiumPrice', models.PositiveIntegerField()),
            ],
        ),
    ]
